language: node_js
node_js: lts/*

cache: yarn

script: yarn build:test

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: www
    on:
      repo: dtom90/GainsTrack
      branch: master